CREATE TABLE IF NOT EXISTS USER_BLOG (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    NAME varchar(255),
    SURNAME varchar(255),
    NICKNAME varchar(255),
    EMAIL varchar(255),
    PRIMARY KEY (USER_ID)
);
CREATE TABLE IF NOT EXISTS POST(
    POST_ID INT NOT NULL AUTO_INCREMENT,
    TITLE varchar(255),
    SUBTITLE varchar(255),
    BODY varchar(255),
    CREATED_AT DATE CURRENT_DATE,
    UPDATED_AT DATE,
    FK_USER_ID INT NOT NULL,
    FOREIGN KEY (FK_USER_ID) REFERENCES USER_BLOG(USER_ID),
    PRIMARY KEY (POST_ID)
);
CREATE TABLE IF NOT EXISTS TAG(
    TAG_ID INT NOT NULL AUTO_INCREMENT,
    TAG varchar(255),
    PRIMARY KEY (TAG_ID)
);
CREATE TABLE IF NOT EXISTS POST_TAG(
    POST_TAG_ID INT NOT NULL AUTO_INCREMENT,
    FK_POST_ID INT,
    FK_TAG_ID INT,
    FOREIGN KEY(FK_POST_ID) REFERENCES POST(POST_ID),
    FOREIGN KEY(FK_TAG_ID) REFERENCES TAG(FK_TAG_ID),
    PRIMARY KEY(POST_TAG_ID)
);